CREATE TABLE `auto_buyer_submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nftAssetId` int NOT NULL,
	`userId` int NOT NULL,
	`platform` varchar(100) NOT NULL,
	`platformUrl` text,
	`submissionId` varchar(200),
	`offeredPrice` decimal(18,8),
	`currency` varchar(10) DEFAULT 'USD',
	`status` enum('pending','submitted','under_review','accepted','rejected','sold') DEFAULT 'pending',
	`rejectionReason` text,
	`earnings` decimal(10,2) DEFAULT '0',
	`isPaidOut` boolean DEFAULT false,
	`submittedAt` timestamp,
	`reviewedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `auto_buyer_submissions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `nft_assets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(200) NOT NULL,
	`description` text,
	`imageUrl` text NOT NULL,
	`imageKey` varchar(500),
	`thumbnailUrl` text,
	`category` varchar(100) NOT NULL,
	`style` varchar(100),
	`traits` json,
	`tokenId` varchar(100),
	`contractAddress` varchar(42),
	`chain` enum('ethereum','polygon','arbitrum','optimism','base','solana') DEFAULT 'ethereum',
	`metadataUri` text,
	`estimatedValue` decimal(18,8) DEFAULT '0',
	`floorPrice` decimal(18,8),
	`lastSalePrice` decimal(18,8),
	`status` enum('generating','generated','minting','minted','listed','sold','burned') DEFAULT 'generating',
	`isMinted` boolean DEFAULT false,
	`views` int DEFAULT 0,
	`likes` int DEFAULT 0,
	`offers` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `nft_assets_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `nft_listings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nftAssetId` int NOT NULL,
	`userId` int NOT NULL,
	`marketplace` varchar(100) NOT NULL,
	`listingUrl` text,
	`listingId` varchar(200),
	`listPrice` decimal(18,8) NOT NULL,
	`currency` varchar(10) DEFAULT 'ETH',
	`expectedSalePrice` decimal(18,8),
	`status` enum('pending','active','sold','cancelled','expired') DEFAULT 'pending',
	`listedAt` timestamp,
	`expiresAt` timestamp,
	`soldAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `nft_listings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `nft_sales` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nftAssetId` int NOT NULL,
	`nftListingId` int,
	`userId` int NOT NULL,
	`marketplace` varchar(100) NOT NULL,
	`salePrice` decimal(18,8) NOT NULL,
	`currency` varchar(10) DEFAULT 'ETH',
	`buyerAddress` varchar(42),
	`txHash` varchar(66),
	`blockNumber` int,
	`marketplaceFee` decimal(18,8),
	`royaltyFee` decimal(18,8),
	`netProceeds` decimal(18,8),
	`isPaidOut` boolean DEFAULT false,
	`payoutTxHash` varchar(66),
	`soldAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `nft_sales_id` PRIMARY KEY(`id`)
);
