CREATE TABLE `crypto_transaction_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`txHash` varchar(66),
	`direction` enum('incoming','outgoing') NOT NULL,
	`txType` enum('deposit','withdrawal','nft_mint','nft_sale','gas_fee','transfer','contract_deploy') NOT NULL,
	`network` varchar(50) NOT NULL,
	`chainId` int NOT NULL,
	`fromAddress` varchar(42) NOT NULL,
	`toAddress` varchar(42) NOT NULL,
	`amount` varchar(78) NOT NULL,
	`amountFormatted` varchar(50) NOT NULL,
	`currency` varchar(10) NOT NULL,
	`usdValue` decimal(18,2),
	`gasUsed` varchar(50),
	`gasPrice` varchar(50),
	`gasCost` varchar(50),
	`gasCostUsd` decimal(18,4),
	`blockNumber` int,
	`blockHash` varchar(66),
	`blockTimestamp` timestamp,
	`status` enum('pending','confirming','confirmed','failed','dropped') NOT NULL DEFAULT 'pending',
	`confirmations` int DEFAULT 0,
	`requiredConfirmations` int DEFAULT 12,
	`firstSeenAt` timestamp,
	`confirmedAt` timestamp,
	`explorerUrl` text,
	`userId` int,
	`nftAssetId` int,
	`relatedTxId` int,
	`description` text,
	`metadata` json,
	`errorMessage` text,
	`retryCount` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `crypto_transaction_log_id` PRIMARY KEY(`id`),
	CONSTRAINT `crypto_transaction_log_txHash_unique` UNIQUE(`txHash`)
);
