CREATE TABLE `nft_earnings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`nftId` varchar(100),
	`tokenId` varchar(100),
	`contractAddress` varchar(100),
	`salePrice` varchar(100) NOT NULL,
	`currency` varchar(20) NOT NULL,
	`marketplace` varchar(100),
	`buyerAddress` varchar(100),
	`transactionHash` varchar(100),
	`blockNumber` int,
	`netEarnings` varchar(100),
	`fees` varchar(100),
	`status` enum('pending','confirmed','transferred') NOT NULL DEFAULT 'pending',
	`transferTxHash` varchar(100),
	`transferredToWallet` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `nft_earnings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `nft_mints` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`tokenId` varchar(100) NOT NULL,
	`contractAddress` varchar(100) NOT NULL,
	`transactionHash` varchar(100) NOT NULL,
	`blockNumber` int,
	`blockHash` varchar(100),
	`network` varchar(50) NOT NULL,
	`name` varchar(500) NOT NULL,
	`description` text,
	`imageUrl` text,
	`metadataUrl` text,
	`category` varchar(100),
	`rarity` varchar(50),
	`gasUsed` varchar(100),
	`gasCost` varchar(100),
	`status` enum('minted','listed','sold','transferred') NOT NULL DEFAULT 'minted',
	`listedOn` json,
	`listingUrls` json,
	`currentPrice` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `nft_mints_id` PRIMARY KEY(`id`)
);
