CREATE TABLE `notification_preferences` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`inAppEnabled` boolean NOT NULL DEFAULT true,
	`inAppNftSold` boolean NOT NULL DEFAULT true,
	`inAppNftPurchased` boolean NOT NULL DEFAULT true,
	`inAppPriceAlert` boolean NOT NULL DEFAULT true,
	`inAppNewListing` boolean NOT NULL DEFAULT true,
	`inAppArticle` boolean NOT NULL DEFAULT true,
	`inAppPayment` boolean NOT NULL DEFAULT true,
	`inAppSystem` boolean NOT NULL DEFAULT true,
	`inAppPromotion` boolean NOT NULL DEFAULT false,
	`emailEnabled` boolean NOT NULL DEFAULT true,
	`emailNftSold` boolean NOT NULL DEFAULT true,
	`emailNftPurchased` boolean NOT NULL DEFAULT true,
	`emailPriceAlert` boolean NOT NULL DEFAULT false,
	`emailNewListing` boolean NOT NULL DEFAULT false,
	`emailArticle` boolean NOT NULL DEFAULT false,
	`emailPayment` boolean NOT NULL DEFAULT true,
	`emailWeeklySummary` boolean NOT NULL DEFAULT true,
	`pushEnabled` boolean NOT NULL DEFAULT false,
	`pushSubscription` json,
	`pushNftSold` boolean NOT NULL DEFAULT true,
	`pushNftPurchased` boolean NOT NULL DEFAULT true,
	`pushPriceAlert` boolean NOT NULL DEFAULT true,
	`pushPayment` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `notification_preferences_id` PRIMARY KEY(`id`),
	CONSTRAINT `notification_preferences_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `notifications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`type` enum('nft_sold','nft_purchased','price_alert','new_listing','article_published','article_distributed','payment_received','payment_sent','system','promotion') NOT NULL,
	`title` varchar(200) NOT NULL,
	`message` text NOT NULL,
	`linkUrl` text,
	`linkText` varchar(100),
	`relatedNftId` int,
	`relatedArticleId` int,
	`relatedPaymentId` int,
	`metadata` json,
	`isRead` boolean NOT NULL DEFAULT false,
	`readAt` timestamp,
	`emailSent` boolean DEFAULT false,
	`emailSentAt` timestamp,
	`pushSent` boolean DEFAULT false,
	`pushSentAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `notifications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `push_subscriptions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`endpoint` text NOT NULL,
	`p256dhKey` text NOT NULL,
	`authKey` text NOT NULL,
	`userAgent` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`lastUsed` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `push_subscriptions_id` PRIMARY KEY(`id`)
);
