CREATE TABLE `backtest_runs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`runId` varchar(64) NOT NULL,
	`symbol` varchar(20) NOT NULL,
	`timeframe` varchar(10) NOT NULL,
	`trainBars` int NOT NULL,
	`testBars` int NOT NULL,
	`windowCount` int NOT NULL DEFAULT 0,
	`totalCandles` int NOT NULL DEFAULT 0,
	`initialCapital` double NOT NULL,
	`finalCapital` double NOT NULL,
	`sharpe` double,
	`sortino` double,
	`maxDrawdown` double,
	`winRate` double,
	`profitFactor` double,
	`cagr` double,
	`totalNetPnl` double,
	`totalTrades` int DEFAULT 0,
	`deflatedSharpe` double,
	`nVariantsTested` int DEFAULT 3,
	`commissionFlat` double,
	`commissionPct` double,
	`slippagePct` double,
	`windowSummaries` json,
	`aggregateEquityCurve` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `backtest_runs_id` PRIMARY KEY(`id`),
	CONSTRAINT `backtest_runs_runId_unique` UNIQUE(`runId`)
);
--> statement-breakpoint
CREATE TABLE `backtest_trades` (
	`id` int AUTO_INCREMENT NOT NULL,
	`runId` varchar(64) NOT NULL,
	`windowIndex` int NOT NULL,
	`entryTime` bigint NOT NULL,
	`exitTime` bigint NOT NULL,
	`entryPrice` double NOT NULL,
	`exitPrice` double NOT NULL,
	`direction` enum('LONG','SHORT') NOT NULL DEFAULT 'LONG',
	`shares` int NOT NULL,
	`grossPnl` double NOT NULL,
	`commission` double NOT NULL,
	`slippage` double NOT NULL,
	`netPnl` double NOT NULL,
	`exitReason` enum('SIGNAL','STOP_LOSS','TAKE_PROFIT','END_OF_WINDOW') NOT NULL,
	`strategy` varchar(30) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `backtest_trades_id` PRIMARY KEY(`id`)
);
